SELECT d.LOCATION, 
	r.RISK_GROUP,
    COUNT(*) AS TOTAL_PATIENTS
FROM demographics d
JOIN risk_groups as r ON d.RECORD_ID = r.RECORD_ID
GROUP BY d.LOCATION, r.RISK_GROUP
ORDER BY d.LOCATION, TOTAL_PATIENTS DESC;
