SELECT	
	SUM(SMOKING) AS SMOKERS,
    SUM(ALCOHOL) AS ALCOHOL_DRINKERS,
    SUM(DM) AS DIABETIC_PATIENTS,
    SUM(HTN) AS HTN_PATIENTS,
    SUM(CAD) AS CAD_PATIENTS,
    SUM(PRIOR_CMP) AS PRIOR_CMP_PATIENTS,
    SUM(CKD) AS CKD_PATIENTS,
    SUM(STEMI) AS STEMI_PATIENTS,
    SUM(HEART_FAILURE) AS HEART_FAILURE_PATIENTS,
    SUM(AKI) AS AKI_PATIENTS,
    SUM(CVA_INFRACT) AS CVA_INFRACT_PATIENTS,
    SUM(CVA_BLEED) AS CVA_BLEED_PATIENTS,
    SUM(PULMONARY_EMBOLISM) AS PULMONARY_EMBOLISM_PATIENTS
FROM health_factors;