SELECT DATE_FORMAT(p.DOA, '%Y-%m') AS MONTH_YEAR, r.RISK_GROUP, COUNT(*) AS TOTAL_PATIENTS
FROM patient_data p
JOIN risk_groups r ON p.RECORD_ID = r.RECORD_ID
WHERE r.RISK_GROUP = 'HIGH'
GROUP BY MONTH_YEAR, r.RISK_GROUP
ORDER BY MONTH_YEAR;